DROP TABLE IF EXISTS SECTION_ENTITY;
 
CREATE TABLE SECTION_ENTITY (
  id VARCHAR(50) AUTO_INCREMENT  PRIMARY KEY,
  ACTIVE BOOLEAN,
  DESCRIPTION_FOOTER VARCHAR(1000) NOT NULL,
  DESCRIPTION_UPPER VARCHAR(1000) NOT NULL,
  IMAGE BLOB DEFAULT NULL, 
  TIME_END TIMESTAMP, 
  TIME_START TIMESTAMP, 
  TITLE VARCHAR(60) DEFAULT NULL
);

INSERT INTO SECTION_ENTITY 
	( ID , ACTIVE , DESCRIPTION_FOOTER , DESCRIPTION_UPPER , IMAGE , TIME_END , TIME_START , TITLE ) 
VALUES  ( "ID3" , FALSE, "DESC1","DESC2","IMAGE",parsedatetime("22-09-2020 18:47:52.69", "dd-MM-yyyy hh:mm:ss.SS"),parsedatetime("22-09-2020 18:47:52.69", "dd-MM-yyyy hh:mm:ss.SS"),"TITLE");

INSERT INTO "PUBLIC"."SECTION_ENTITY"("ID","ACTIVE","DESCRIPTION_FOOTER","DESCRIPTION_UPPER","IMAGE","TIME_END","TIME_START","TITLE")VALUES("ID3" , FALSE, "DESC1","DESC2","IMAGE",parsedatetime("22-09-2020 18:47:52.69", "dd-MM-yyyy hh:mm:ss.SS"),parsedatetime("22-09-2020 18:47:52.69", "dd-MM-yyyy hh:mm:ss.SS"),"TITLE")